Add basic global functions to SDK
CKS-Systems/manifest pull request #97
Opened 2024-09-17 00:23 UTC by DonDuala

2024-09-17 12:21 UTC, brittcyr approved these changes

2024-09-17 12:21 UTC, brittcyr commented on client/ts/src/client.ts
> +    const is22: boolean = mintInfo.tlvData.length > 0;
TODO for a helper function for is22

2024-09-17 12:21 UTC, brittcyr commented on client/ts/src/client.ts
> +   * CreateGlobalAddTrader instruction.
explain. this one isnt so self explanatory from the name

2024-09-17 12:21 UTC, brittcyr commented on client/ts/src/global.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
what are the unused vars?

2024-09-17 12:21 UTC, brittcyr commented on client/ts/src/global.ts
> +  async getGlobalBalanceTokens(
document function

2024-09-17 12:21 UTC, brittcyr commented on client/ts/src/global.ts
> +  getUnclaimedGasTokens(trader: PublicKey): number {
dont expose this. probably gonna remove

2024-09-17 12:21 UTC, brittcyr commented on client/ts/src/global.ts
> +  async tokenDecimals(connection: Connection): Promise<number> {
cache this

2024-09-17 12:21 UTC, brittcyr commented on client/ts/src/global.ts
> +  private static deserializeGlobalBuffer(data: Buffer): GlobalData {
comment linking to code where this is defined in rust

2024-09-17 12:21 UTC, brittcyr commented on client/ts/src/global.ts
> +    const numSeatsClaimed = data.readInt16LE(offset);
might be a UInt16LE, not sure

2024-09-17 12:21 UTC, brittcyr commented on client/ts/tests/globalithdraw.ts
> +import {
filename

2024-09-17 12:21 UTC, brittcyr commented on debug-ui/.env.local
this and other debug-ui, remove

2024-09-17 12:33 UTC, DonDuala commented on client/ts/src/client.ts
> +    const is22: boolean = mintInfo.tlvData.length > 0;
added comment

2024-09-20 01:10 UTC, brittcyr commented on client/ts/tests/createGlobal.ts
> +export async function createGlobal(
make this be able to take a mint as an input so it can be used in other tests

2024-09-22 05:35 UTC, brittcyr commented on client/ts/tests/createGlobal.ts
> +  const globalKeypair: Keypair = Keypair.generate();
No reason to have a globalKeypair. The global account is at a PDA. Return from this function, if you want it to be the global address, should be
getGlobalAddress(tokenMint)

also, no need to initialize an empty program account here.

2024-09-22 05:35 UTC, brittcyr commented on client/ts/tests/createGlobal.ts
> +  const globalKeypair: Keypair = Keypair.generate();
we call account create inside the global create handler

https://github.com/CKS-Systems/manifest/blob/e9a7e710582aba85042086890aa99acf5760abad/programs/manifest/src/program/processor/global_create.rs#L41

2024-09-22 05:37 UTC, brittcyr commented
The reason that the test was failing was that you were attempting to deserialize at the wrong address. We dont have a separate keypair for a global account because it is not a throw-away-able account. You initialize an empty account, which ends up in an infinite loop walking the red black tree at position zero.

2024-09-26 11:21 UTC, brittcyr requested changes
I can follow through on the fixes from earlier comment if you want me to

2024-09-27 16:57 UTC, DonDuala commented
> I can follow through on the fixes from earlier comment if you want me to

Please do, focused on RM changes and BD

2024-10-02 10:56 UTC, brittcyr approved these changes

2024-10-02 15:26 UTC, merged